[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "arxiv_scan/_version.py"

[tool.mypy]
files = "arxiv_scan"
strict = true
implicit_reexport = true
